### ISSUE TITLE
Getting an error when running

### ISSUE THREAD

**Issue by Cunpa** [Kinuseka/NHentaiAPI#10]
Log file is attached

[[2023-09-16 11.10.12]LogFile.log](https://github.com/Kinuseka/nScraper/files/12639804/2023-09-16.11.10.12.LogFile.log)

**Comment by Kinuseka** [comment]
The error shows that it cannot find chromium/chrome binary file on `PATH`

Do you have chromium or chrome installed?

**Comment by Cunpa** [comment]
That was the problem. I didn't have Chrome installed.
